### ISSUE TITLE
两个设备连接到同频段WIFI下无法PING通对方

### ISSUE THREAD

**Issue by zhipengzhong** [w2xg2022/ax18usb#3]
我这边ZN-M2刷入固件后，电视投屏功能无法使用，排查发现当电视和手机同时连到5G WIFI 或者同时连到 2.4G WIFI的时候是无法通信的，ping也不通。请问这个问题能解决吗

**Comment by w2xg2022** [comment]
没有发现类似问题。

测试条件：
1、AX18开启5G，信道36、80MHz
2、Realme手机、E900V22C盒子都连上同一个无线
3、手机可以通过当贝桌面向盒子上传APK，也能投屏（盒子用萝卜投屏，手机用系统自带投屏功能）

**Comment by zhipengzhong** [comment]
抱歉，才收到邮件提醒。

我尝试了你编译好的固件，和手动编译了你仓库和lean的仓库都是不行，我尝试了android ping android，android ping PC，android ping IOS，PC ping android，PC ping IOS，操作终端和目标终端连接不同频段Wifi有正常响应，同频段不行，基本可以排除是终端设备的问题。

应该是ZN-M2的问题，或者是我改硬件留下了什么后遗症。我这边暂时没有和目AX18和其他ZN-M2可以验证了。现在的解决方案是把投影和手机连到不同的频段下使用。后面有机会再搞个和目的路由试试看。

最后，感谢你的验证和回复。
